export const hardcodedLessons = [
  {
    name: "Αγγλικά - Προπαρασκευαστικό",
    code: "1004",
    type: "Προπαρασκευαστικό (ΠΡ)",
    ects: "0",
    semester: "1",
    selected: false,
  },
  {
    name: "Ιστορία Design I",
    code: "1253",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "1",
    selected: false,
  },
  {
    name: "Στούντιο 1A - Σχέδιο Χρώμα",
    code: "1307",
    type: "Υποχρεωτικό (Υ)",
    ects: "4",
    semester: "1",
    selected: false,
  },
  {
    name: "Πληροφορική",
    code: "2155",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "1",
    selected: false,
  },
  {
    name: "Θεωρία και Μεθοδολογία Σχεδίασης",
    code: "2204",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "1",
    selected: false,
  },
  {
    name: "Στούντιο 1Β - Ελεύθερο Σχέδιο",
    code: "2454",
    type: "Υποχρεωτικό (Υ)",
    ects: "2",
    semester: "1",
    selected: false,
  },
  {
    name: "Μαθηματικά Ι",
    code: "3055",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "1",
    selected: false,
  },
  {
    name: "Ιστορία Design II",
    code: "2252",
    type: "Υποχρεωτικό (Υ)",
    ects: "4",
    semester: "2",
    selected: false,
  },
  {
    name: "Στούντιο 2A - Σχέδιο Χρώμα",
    code: "2306",
    type: "Υποχρεωτικό (Υ)",
    ects: "4",
    semester: "2",
    selected: false,
  },
  {
    name: "Αγγλικά - Ορολογία",
    code: "2354",
    type: "Υποχρεωτικό (Υ)",
    ects: "2",
    semester: "2",
    selected: false,
  },
  {
    name: "Μαθηματικά ΙΙ",
    code: "3453",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "2",
    selected: false,
  },
  {
    name: "Στούντιο 2Β - Ελεύθερο Σχέδιο",
    code: "3500",
    type: "Υποχρεωτικό (Υ)",
    ects: "2",
    semester: "2",
    selected: false,
  },
  {
    name: "Συστημική Θεωρία",
    code: "4053",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "2",
    selected: false,
  },
  {
    name: "Τεχνολογίες και Μεθοδολογίες Προγραμματισμού",
    code: "4203",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "2",
    selected: false,
  },
  {
    name: "Φυσική για Μηχανικούς",
    code: "1403",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "3",
    selected: false,
  },
  {
    name: "Εισαγωγή στη Σχεδίαση με Η/Υ (CAGD)",
    code: "2404",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "3",
    selected: false,
  },
  {
    name: "Στούντιο 3 - Ιδεασμός",
    code: "3254",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "3",
    selected: false,
  },
  {
    name: "Σχεδίαση και Ανάπτυξη Πληροφοριακών Συστημάτων",
    code: "5003",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "3",
    selected: false,
  },
  {
    name: "Marketing",
    code: "6355",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "3",
    selected: false,
  },
  {
    name: "Στούντιο 4 - Concept Design",
    code: "4304",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "4",
    selected: false,
  },
  {
    name: "Σχεδίαση με Η/Υ",
    code: "5153",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "4",
    selected: false,
  },
  {
    name: "Αλληλεπίδραση Ανθρώπου Υπολογιστή",
    code: "6104",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "4",
    selected: false,
  },
  {
    name: "Θεωρία Πολύπλοκων Οργανώσεων",
    code: "7258",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "4",
    selected: false,
  },
  {
    name: "Γνωστική Επιστήμη",
    code: "8154",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "4",
    selected: false,
  },
  {
    name: "Τεχνική Μηχανική",
    code: "3405",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "5",
    selected: false,
  },
  {
    name: "Στούντιο 5 - Product Design I",
    code: "5303",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "5",
    selected: false,
  },
  {
    name: "Γραφικά",
    code: "6153",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "5",
    selected: false,
  },
  {
    name: "Σχεδίαση Υπηρεσιών",
    code: "6203",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "5",
    selected: false,
  },
  {
    name: "Εργονομία",
    code: "7204",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "5",
    selected: false,
  },
  {
    name: "Διαδραστική Σχεδίαση",
    code: "4153",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "6",
    selected: false,
  },
  {
    name: "Υλικά",
    code: "4356",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "6",
    selected: false,
  },
  {
    name: "Στούντιο 6 - Product Design II",
    code: "6303",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "6",
    selected: false,
  },
  {
    name: "Ανάλυση & Κατασκευή Προϊόντων με Η/Υ (CAE/CAM)",
    code: "8452",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "6",
    selected: false,
  },
  {
    name: "Οικοδόμηση και Διοίκηση Μαρκών",
    code: "9905",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "6",
    selected: false,
  },
  {
    name: "Αγγλικά για Ειδικούς Σκοπούς",
    code: "3304",
    type: "Υποχρεωτικό (Υ)",
    ects: "2",
    semester: "7",
    selected: false,
  },
  {
    name: "Μηχανική και Υλικά στον Σχεδιασμό",
    code: "5204",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 2 (ΥΕΚ2)",
    ects: "5",
    semester: "7",
    selected: false,
  },
  {
    name: "Ειδικά Θέματα Υλικών",
    code: "7354",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "7",
    selected: false,
  },
  {
    name: "Σχεδίαση και Οργάνωση Εκθέσεων",
    code: "7950",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "7",
    selected: false,
  },
  {
    name: "Επιχειρηματικότητα",
    code: "8014",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 3 (ΥΕΚ3)",
    ects: "5",
    semester: "7",
    selected: false,
  },
  {
    name: "Βάσεις Δεδομένων και Εξόρυξη Γνώσης",
    code: "8605",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "7",
    selected: false,
  },
  {
    name: "Σχεδιασμός και Ανάλυση Μηχανισμών",
    code: "8854",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 2 (ΥΕΚ2)",
    ects: "5",
    semester: "7",
    selected: false,
  },
  // {
  //   name: "Πρακτική Άσκηση",
  //   code: "8902",
  //   type: "Υποχρεωτικό (Υ)",
  //   ects: "8",
  //   semester: "7",
  //   selected: false,
  // },
  {
    name: "Συμπεριφορά Καταναλωτή",
    code: "9304",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 3 (ΥΕΚ3)",
    ects: "5",
    semester: "7",
    selected: false,
  },
  {
    name: "Μηχανοτρονική",
    code: "9353",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 2 (ΥΕΚ2)",
    ects: "5",
    semester: "7",
    selected: false,
  },
  {
    name: "Προηγμένες Τεχνολογίες Αλληλεπίδρασης και Εφαρμογές",
    code: "9803",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 1 (ΥΕΚ1)",
    ects: "5",
    semester: "7",
    selected: false,
  },
  {
    name: "Συμμετοχική Σχεδίαση και Πρωτοτυποποίηση Υπηρεσιών",
    code: "10400",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "5",
    semester: "7",
    selected: false,
  },
  {
    name: "Διακριτά Μαθηματικά",
    code: "3353",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "8",
    selected: false,
  },
  {
    name: "Ακαδημαϊκά Αγγλικά I",
    code: "4011",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "2",
    semester: "8",
    selected: false,
  },
  {
    name: "Τεχνικό Σχέδιο",
    code: "4502",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 2 (ΥΕΚ2)",
    ects: "5",
    semester: "8",
    selected: false,
  },
  {
    name: "Ιστορία Τέχνης Ι",
    code: "5053",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "8",
    selected: false,
  },
  {
    name: "Σχεδίαση και Προγραμματισμός για τον Παγκόσμιο Ιστό",
    code: "6404",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 1 (ΥΕΚ1)",
    ects: "5",
    semester: "8",
    selected: false,
  },
  {
    name: "Αλγόριθμοι και Δομές Δεδομένων",
    code: "7055",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "8",
    selected: false,
  },
  {
    name: "Σχεδίαση για όλους",
    code: "7154",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 3 (ΥΕΚ3)",
    ects: "5",
    semester: "8",
    selected: false,
  },
  {
    name: "Ψηφιακές Μορφές Αφήγησης",
    code: "7554",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 1 (ΥΕΚ1)",
    ects: "5",
    semester: "8",
    selected: false,
  },
  {
    name: "Ψηφιακή Πολιτιστική Κληρονομιά",
    code: "7901",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "8",
    selected: false,
  },
  {
    name: "Σχεδίαση και Προγραμματισμός Εφαρμογών για Φορητές Συσκευές",
    code: "8056",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 1 (ΥΕΚ1)",
    ects: "5",
    semester: "8",
    selected: false,
  },
  {
    name: "Παραστατική Κινηματογραφία (Animation)",
    code: "8205",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "8",
    selected: false,
  },
  {
    name: "Ρομποτική",
    code: "8253",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 2 (ΥΕΚ2)",
    ects: "5",
    semester: "8",
    selected: false,
  },
  {
    name: "Σχεδίαση Πληροφορίας",
    code: "8802",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 3 (ΥΕΚ3)",
    ects: "5",
    semester: "8",
    selected: false,
  },
  {
    name: "Πρακτική Άσκηση",
    code: "8902",
    type: "Υποχρεωτικό (Υ)",
    ects: "8",
    semester: "8",
    selected: false,
  },
  {
    name: "Σχεδίαση για Αειφορία και Κυκλική Οικονομία",
    code: "9012",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "8",
    selected: false,
  },
  {
    name: "Υλικά, Τεχνικές και Μέσα Παρουσίασης",
    code: "9254",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "8",
    selected: false,
  },
  {
    name: "Συστήματα Υποστήριξης Αποφάσεων",
    code: "9453",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 3 (ΥΕΚ3)",
    ects: "5",
    semester: "8",
    selected: false,
  },
  {
    name: "Σχεδίαση και Τεχνολογίες Παραγωγής",
    code: "9503",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 2 (ΥΕΚ2)",
    ects: "5",
    semester: "8",
    selected: false,
  },
  {
    name: "Εικονική Πραγματικότητα",
    code: "9554",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 1 (ΥΕΚ1)",
    ects: "5",
    semester: "8",
    selected: false,
  },
  {
    name: "Σχεδίαση για προσθετική κατασκευή προϊόντων",
    code: "10152",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "8",
    selected: false,
  },
  {
    name: "Αισθητική και Συναισθηματική Σχεδίαση",
    code: "10302",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 3 (ΥΕΚ3)",
    ects: "5",
    semester: "8",
    selected: false,
  },
  {
    name: "Ιστορία Τέχνης ΙΙ",
    code: "6054",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "9",
    selected: false,
  },
  {
    name: "Στούντιο 7α - Σχεδίαση Διαδραστικών Συστημάτων",
    code: "7313",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 1 (ΥΕΚ1)",
    ects: "8",
    semester: "9",
    selected: false,
  },
  {
    name: "Στούντιο 7β - Λεπτομερής Βιομηχανικός Σχεδιασμός",
    code: "7323",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 2 (ΥΕΚ2)",
    ects: "8",
    semester: "9",
    selected: false,
  },
  {
    name: "Στούντιο 7γ - Σχεδίαση Υπηρεσιών",
    code: "7333",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 3 (ΥΕΚ3)",
    ects: "8",
    semester: "9",
    selected: false,
  },
  {
    name: "Γραφιστική",
    code: "7404",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "9",
    selected: false,
  },
  {
    name: "Τεχνητή Νοημοσύνη",
    code: "8553",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "9",
    selected: false,
  },
  {
    name: "Σχεδίαση Οχημάτων & Νέες Τεχνολογίες Υποστήριξης Οδηγού",
    code: "8754",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "9",
    selected: false,
  },
  {
    name: "Πρακτική Άσκηση (συνεχιζόμενη)",
    code: "8952",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "0",
    semester: "9",
    selected: false,
  },
  {
    name: "Νομικά στο Design",
    code: "9103",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "9",
    selected: false,
  },
  {
    name: "Τεχνολογική Υποστήριξη της Συνεργατικής Εργασίας",
    code: "9403",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "9",
    selected: false,
  },
  {
    name: "Πληροφορική Κινηματογραφία (Computer Animation)",
    code: "9605",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "9",
    selected: false,
  },
  {
    name: "Ψηφιακά Παιχνίδια και Παιγνιώδης Μάθηση",
    code: "9854",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 1 (ΥΕΚ1)",
    ects: "5",
    semester: "9",
    selected: false,
  },
  {
    name: "Συστημική Σκέψη στην Σχεδίαση",
    code: "10250",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "9",
    selected: false,
  },
  {
    name: "Φιλοσοφία, Θεωρία, Επιστημολογία Σχεδίασης",
    code: "10350",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "9",
    selected: false,
  },
  {
    name: "Ακαδημαϊκά Αγγλικά ΙΙ",
    code: "10200",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "2",
    semester: "8",
    selected: false,
  },
  {
    name: "Διπλωματική",
    code: "10903",
    type: "Υποχρεωτικό (Υ)",
    ects: "30",
    semester: "10",
    selected: false,
  },
];

export const hardcodedSemesterToggles = [
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
];
