export const hardcoded = [
  {
    name: "Αγγλικά - Προπαρασκευαστικό",
    type: "Προπαρασκευαστικό (ΠΡ)",
    ects: "0",
    semester: "1",
    selected: true,
  },
  {
    name: "Ιστορία Design I",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "1",
    selected: true,
  },
  {
    name: "Στούντιο 1A - Σχέδιο Χρώμα",
    type: "Υποχρεωτικό (Υ)",
    ects: "4",
    semester: "1",
    selected: true,
  },
  {
    name: "Πληροφορική",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "1",
    selected: true,
  },
  {
    name: "Θεωρία και Μεθοδολογία Σχεδίασης",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "1",
    selected: true,
  },
  {
    name: "Στούντιο 1Β - Ελεύθερο Σχέδιο",
    type: "Υποχρεωτικό (Υ)",
    ects: "2",
    semester: "1",
    selected: true,
  },
  {
    name: "Μαθηματικά Ι",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "1",
    selected: true,
  },
  {
    name: "Ιστορία Design II",
    type: "Υποχρεωτικό (Υ)",
    ects: "4",
    semester: "2",
    selected: true,
  },
  {
    name: "Στούντιο 2A - Σχέδιο Χρώμα",
    type: "Υποχρεωτικό (Υ)",
    ects: "4",
    semester: "2",
    selected: true,
  },
  {
    name: "Αγγλικά - Ορολογία",
    type: "Υποχρεωτικό (Υ)",
    ects: "2",
    semester: "2",
    selected: true,
  },
  {
    name: "Μαθηματικά ΙΙ",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "2",
    selected: true,
  },
  {
    name: "Στούντιο 2Β - Ελεύθερο Σχέδιο",
    type: "Υποχρεωτικό (Υ)",
    ects: "2",
    semester: "2",
    selected: false,
  },
  {
    name: "Συστημική Θεωρία",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "2",
    selected: true,
  },
  {
    name: "Τεχνολογίες και Μεθοδολογίες Προγραμματισμού",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "2",
    selected: true,
  },
  {
    name: "Φυσική για Μηχανικούς",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "3",
    selected: false,
  },
  {
    name: "Εισαγωγή στη Σχεδίαση με Η/Υ (CAGD)",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "3",
    selected: true,
  },
  {
    name: "Στούντιο 3 - Ιδεασμός",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "3",
    selected: true,
  },
  {
    name: "Σχεδίαση και Ανάπτυξη Πληροφοριακών Συστημάτων",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "3",
    selected: true,
  },
  {
    name: "Marketing",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "3",
    selected: true,
  },
  {
    name: "Στούντιο 4 - Concept Design",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "4",
    selected: true,
  },
  {
    name: "Σχεδίαση με Η/Υ",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "4",
    selected: true,
  },
  {
    name: "Αλληλεπίδραση Ανθρώπου Υπολογιστή",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "4",
    selected: true,
  },
  {
    name: "Θεωρία Πολύπλοκων Οργανώσεων",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "4",
    selected: true,
  },
  {
    name: "Γνωστική Επιστήμη",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "4",
    selected: false,
  },
  {
    name: "Τεχνική Μηχανική",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "5",
    selected: true,
  },
  {
    name: "Στούντιο 5 - Product Design I",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "5",
    selected: true,
  },
  {
    name: "Γραφικά",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "5",
    selected: true,
  },
  {
    name: "Σχεδίαση Υπηρεσιών",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "5",
    selected: true,
  },
  {
    name: "Εργονομία",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "5",
    selected: false,
  },
  {
    name: "Διαδραστική Σχεδίαση",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "6",
    selected: true,
  },
  {
    name: "Υλικά",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "6",
    selected: false,
  },
  {
    name: "Στούντιο 6 - Product Design II",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "6",
    selected: true,
  },
  {
    name: "Ανάλυση & Κατασκευή Προϊόντων με Η/Υ (CAE/CAM)",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "6",
    selected: false,
  },
  {
    name: "Οικοδόμηση και Διοίκηση Μαρκών",
    type: "Υποχρεωτικό (Υ)",
    ects: "6",
    semester: "6",
    selected: false,
  },
  {
    name: "Αγγλικά για Ειδικούς Σκοπούς",
    type: "Υποχρεωτικό (Υ)",
    ects: "2",
    semester: "7",
    selected: true,
  },
  {
    name: "Μηχανική και Υλικά στον Σχεδιασμό",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 2 (ΥΕΚ2)",
    ects: "5",
    semester: "7",
    selected: false,
  },
  {
    name: "Ειδικά Θέματα Υλικών",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "7",
    selected: false,
  },
  {
    name: "Σχεδίαση και Οργάνωση Εκθέσεων",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "7",
    selected: false,
  },
  {
    name: "Επιχειρηματικότητα",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 3 (ΥΕΚ3)",
    ects: "5",
    semester: "7",
    selected: false,
  },
  {
    name: "Βάσεις Δεδομένων και Εξόρυξη Γνώσης",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "7",
    selected: false,
  },
  {
    name: "Σχεδιασμός και Ανάλυση Μηχανισμών",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 2 (ΥΕΚ2)",
    ects: "5",
    semester: "7",
    selected: false,
  },
  {
    name: "Πρακτική Άσκηση",
    type: "Υποχρεωτικό (Υ)",
    ects: "8",
    semester: "7",
    selected: false,
  },
  {
    name: "Συμπεριφορά Καταναλωτή",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 3 (ΥΕΚ3)",
    ects: "5",
    semester: "7",
    selected: false,
  },
  {
    name: "Μηχανοτρονική",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 2 (ΥΕΚ2)",
    ects: "5",
    semester: "7",
    selected: false,
  },
  {
    name: "Προηγμένες Τεχνολογίες Αλληλεπίδρασης και Εφαρμογές",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 1 (ΥΕΚ1)",
    ects: "5",
    semester: "7",
    selected: true,
  },
  {
    name: "Συμμετοχική Σχεδίαση και Πρωτοτυποποίηση Υπηρεσιών",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "5",
    semester: "7",
    selected: false,
  },
  {
    name: "Διακριτά Μαθηματικά",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "8",
    selected: false,
  },
  {
    name: "Ακαδημαϊκά Αγγλικά 1",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "2",
    semester: "8",
    selected: false,
  },
  {
    name: "Τεχνικό Σχέδιο",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 2 (ΥΕΚ2)",
    ects: "5",
    semester: "8",
    selected: true,
  },
  {
    name: "Ιστορία Τέχνης Ι",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "8",
    selected: false,
  },
  {
    name: "Σχεδίαση και Προγραμματισμός για τον Παγκόσμιο Ιστό",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 1 (ΥΕΚ1)",
    ects: "5",
    semester: "8",
    selected: false,
  },
  {
    name: "Αλγόριθμοι και Δομές Δεδομένων",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "8",
    selected: false,
  },
  {
    name: "Σχεδίαση για όλους",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 3 (ΥΕΚ3)",
    ects: "5",
    semester: "8",
    selected: false,
  },
  {
    name: "Ψηφιακές Μορφές Αφήγησης",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 1 (ΥΕΚ1)",
    ects: "5",
    semester: "8",
    selected: false,
  },
  {
    name: "Ψηφιακή Πολιτιστική Κληρονομιά",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "8",
    selected: false,
  },
  {
    name: "Σχεδίαση και Προγραμματισμός Εφαρμογών για Φορητές Συσκευές",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 1 (ΥΕΚ1)",
    ects: "5",
    semester: "8",
    selected: true,
  },
  {
    name: "Παραστατική Κινηματογραφία (Animation)",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "8",
    selected: false,
  },
  {
    name: "Ρομποτική",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 2 (ΥΕΚ2)",
    ects: "5",
    semester: "8",
    selected: false,
  },
  {
    name: "Σχεδίαση Πληροφορίας",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 3 (ΥΕΚ3)",
    ects: "5",
    semester: "8",
    selected: false,
  },
  {
    name: "Πρακτική Άσκηση",
    type: "Υποχρεωτικό (Υ)",
    ects: "8",
    semester: "8",
    selected: false,
  },
  {
    name: "Σχεδίαση για Αειφορία και Κυκλική Οικονομία",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 3 (ΥΕΚ3)",
    ects: "4",
    semester: "8",
    selected: false,
  },
  {
    name: "Υλικά, Τεχνικές και Μέσα Παρουσίασης",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "8",
    selected: false,
  },
  {
    name: "Συστήματα Υποστήριξης Αποφάσεων",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 3 (ΥΕΚ3)",
    ects: "5",
    semester: "8",
    selected: false,
  },
  {
    name: "Σχεδίαση και Τεχνολογίες Παραγωγής",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 2 (ΥΕΚ2)",
    ects: "5",
    semester: "8",
    selected: false,
  },
  {
    name: "Εικονική Πραγματικότητα",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 1 (ΥΕΚ1)",
    ects: "5",
    semester: "8",
    selected: false,
  },
  {
    name: "Σχεδίαση για προσθετική κατασκευή προϊόντων",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "8",
    selected: false,
  },
  {
    name: "Αισθητική και Συναισθηματική Σχεδίαση",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "5",
    semester: "8",
    selected: false,
  },
  {
    name: "Ιστορία Τέχνης ΙΙ",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "9",
    selected: false,
  },
  {
    name: "Στούντιο 7α - Σχεδίαση Διαδραστικών Συστημάτων",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 1 (ΥΕΚ1)",
    ects: "8",
    semester: "9",
    selected: false,
  },
  {
    name: "Στούντιο 7β - Λεπτομερής Βιομηχανικός Σχεδιασμός",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 2 (ΥΕΚ2)",
    ects: "8",
    semester: "9",
    selected: false,
  },
  {
    name: "Στούντιο 7γ - Σχεδίαση Υπηρεσιών",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 3 (ΥΕΚ3)",
    ects: "8",
    semester: "9",
    selected: false,
  },
  {
    name: "Γραφιστική",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "9",
    selected: false,
  },
  {
    name: "Τεχνητή Νοημοσύνη",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "9",
    selected: true,
  },
  {
    name: "Σχεδίαση Οχημάτων & Νέες Τεχνολογίες Υποστήριξης Οδηγού",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "9",
    selected: false,
  },
  {
    name: "Πρακτική Άσκηση (συνεχιζόμενη)",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "0",
    semester: "9",
    selected: false,
  },
  {
    name: "Νομικά στο Design",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "9",
    selected: true,
  },
  {
    name: "Τεχνολογική Υποστήριξη της Συνεργατικής Εργασίας",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "9",
    selected: false,
  },
  {
    name: "Πληροφορική Κινηματογραφία (Computer Animation)",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "9",
    selected: false,
  },
  {
    name: "Ψηφιακά Παιχνίδια και Παιγνιώδης Μάθηση",
    type: "Υποχρεωτικό Επιλογής Κατεύθυνσης 1 (ΥΕΚ1)",
    ects: "5",
    semester: "9",
    selected: true,
  },
  {
    name: "Συστημική Σκέψη στην Σχεδίαση",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "9",
    selected: false,
  },
  {
    name: "Φιλοσοφία, Θεωρία, Επιστημολογία Σχεδίασης",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "4",
    semester: "9",
    selected: false,
  },
  {
    name: "Ακαδημαϊκά Αγγλικά ΙΙ",
    type: "Ελεύθερης Επιλογής (ΕΕ)",
    ects: "2",
    semester: "10",
    selected: false,
  },
  {
    name: "Διπλωματική",
    type: "Υποχρεωτικό (Υ)",
    ects: "30",
    semester: "10",
    selected: false,
  },
];
