export const defaultHoverItem = {
  Name: "No Hover",
  Semester: 0,
  Room: "hover",
  Code: 0,
  Mon: [],
  Tue: [],
  Wed: [],
  Thu: [],
  Fri: [],
};

export const p_E23_v5 = [
  {
    Name: "Στούντιο 2Α-Β",
    Semester: 2,
    Room: "Ι11",
    Code: 2306,
    Mon: [9, 10, 11],
    Tue: [12, 13, 14],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Στούντιο 2Α-A",
    Semester: 2,
    Room: "Ι11",
    Code: 2306,
    Mon: [12, 13, 14],
    Tue: [9, 10, 11],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Στούντιο 2Β-Α",
    Semester: 2,
    Room: "Ι11",
    Code: 3500,
    Mon: [16, 17],
    Tue: [],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Στούντιο 2Β-Β",
    Semester: 2,
    Room: "Ι11",
    Code: 3500,
    Mon: [18, 19],
    Tue: [],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Αλλ. Ανθρ.-Υπολ. (Θ)",
    Semester: 4,
    Room: "Π11",
    Code: 6104,
    Mon: [9, 10, 11],
    Tue: [],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Σχεδίαση με ΗΥ (Ε)",
    Semester: 4,
    Room: "ΗΥ",
    Code: 5153,
    Mon: [12, 13],
    Tue: [],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Σχεδίαση με ΗΥ (Ε) -Φρ.",
    Semester: 4,
    Room: "ΗΥ",
    Code: 5153,
    Mon: [14, 15],
    Tue: [],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Υλικά (Θ)",
    Semester: 6,
    Room: "Π11",
    Code: 4356,
    Mon: [12, 13],
    Tue: [9],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Αν.& Κατ. Πρ. ΗΥ (Θ)",
    Semester: 6,
    Room: "Β02",
    Code: 8452,
    Mon: [15, 16, 17],
    Tue: [],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Αλγ. Δομές Δεδομένων",
    Semester: 8,
    Room: "ΗΥ",
    Code: 7055,
    Mon: [9, 10, 11],
    Tue: [],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Ρομποτική (Θ)",
    Semester: 8,
    Room: "Β12",
    Code: 8253,
    Mon: [12, 13],
    Tue: [],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Ρομποτική (Ε)",
    Semester: 8,
    Room: "Β12",
    Code: 8253,
    Mon: [14, 15],
    Tue: [],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Σχ.&Τεχ. Παραγωγής(Θ)",
    Semester: 8,
    Room: "Β13",
    Code: 9503,
    Mon: [15, 16],
    Tue: [],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Πρακτική Άσκηση",
    Semester: 8,
    Room: "Β12",
    Code: 8902,
    Mon: [16],
    Tue: [],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Τεχνικό Σχέδιο (Θ)",
    Semester: 8,
    Room: "ΗΥ",
    Code: 4502,
    Mon: [17, 18],
    Tue: [],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Τεχνικό Σχέδιο (Ε)",
    Semester: 8,
    Room: "ΗΥ",
    Code: 4502,
    Mon: [19, 20],
    Tue: [],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Σχ.&Τεχ. Παραγωγής(Ε)",
    Semester: 8,
    Room: "Β13",
    Code: 9503,
    Mon: [19, 20],
    Tue: [],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Αγγλικά-Ορολογία -Α",
    Semester: 2,
    Room: "Β02",
    Code: 2354,
    Mon: [],
    Tue: [16, 17, 18],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Συστημική Θεωρία",
    Semester: 2,
    Room: "Π11",
    Code: 4053,
    Mon: [],
    Tue: [19, 20],
    Wed: [],
    Thu: [11, 12],
    Fri: [],
  },
  {
    Name: "Αλλ. Ανθρ.-Υπολ. (Ε) - Α",
    Semester: 4,
    Room: "ΗΥ",
    Code: 6104,
    Mon: [],
    Tue: [9, 10],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Αλλ. Ανθρ.-Υπολ. (Ε) - Β",
    Semester: 4,
    Room: "ΗΥ",
    Code: 6104,
    Mon: [],
    Tue: [11, 12],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Υλικά (Ε)",
    Semester: 6,
    Room: "Π11",
    Code: 4356,
    Mon: [],
    Tue: [10, 11],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Αν.Κατ.Πρ.ΗΥ(Ε)",
    Semester: 6,
    Room: "ΗΥ/Β02",
    Code: 8452,
    Mon: [],
    Tue: [13, 14],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Εικονική Πραγματ. (Θ)",
    Semester: 8,
    Room: "Β13",
    Code: 9554,
    Mon: [],
    Tue: [13, 14],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Εικονική Πραγματ. (Ε)",
    Semester: 8,
    Room: "ΗΥ",
    Code: 9554,
    Mon: [],
    Tue: [15, 16],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Σχεδ. Φορητές Συσκ.(Θ)",
    Semester: 8,
    Room: "ΗΥ",
    Code: 8056,
    Mon: [],
    Tue: [17, 18],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Σχεδ. Φορητές Συσκ.(Ε)",
    Semester: 8,
    Room: "ΗΥ",
    Code: 8056,
    Mon: [],
    Tue: [19, 20],
    Wed: [],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Τεχν. Μεθ. Προγρ. (Θ)",
    Semester: 2,
    Room: "Π11",
    Code: 4203,
    Mon: [],
    Tue: [],
    Wed: [9, 10, 11],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Τεχν. Μεθ. Προγρ. (Ε)-Α",
    Semester: 2,
    Room: "ΗΥ",
    Code: 4203,
    Mon: [],
    Tue: [],
    Wed: [12, 13],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Τεχν. Μεθ. Προγρ. (Ε)-Β",
    Semester: 2,
    Room: "ΗΥ",
    Code: 4203,
    Mon: [],
    Tue: [],
    Wed: [14, 15],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Σχεδίαση με ΗΥ (Θ)",
    Semester: 4,
    Room: "Β02",
    Code: 5153,
    Mon: [],
    Tue: [],
    Wed: [9, 10, 11],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Θεωρία Πολύπλ. Οργαν.",
    Semester: 4,
    Room: "Π11",
    Code: 7258,
    Mon: [],
    Tue: [],
    Wed: [15, 16],
    Thu: [13, 14],
    Fri: [],
  },
  {
    Name: "Γνωστική Επιστήμη",
    Semester: 4,
    Room: "Π11",
    Code: 8154,
    Mon: [],
    Tue: [],
    Wed: [17, 18],
    Thu: [15, 16],
    Fri: [],
  },
  {
    Name: "Στούντιο 6",
    Semester: 6,
    Room: "Ι12",
    Code: 6303,
    Mon: [],
    Tue: [],
    Wed: [14, 15, 16],
    Thu: [12, 13, 14],
    Fri: [],
  },
  {
    Name: "Οικοδ. Διοίκηση Μαρκών",
    Semester: 6,
    Room: "Β02",
    Code: 9905,
    Mon: [],
    Tue: [],
    Wed: [17, 18],
    Thu: [9, 10],
    Fri: [],
  },
  {
    Name: "Συστ. Υποστ. Αποφ.",
    Semester: 8,
    Room: "Β12",
    Code: 9453,
    Mon: [],
    Tue: [],
    Wed: [9, 10, 11, 12],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Σχεδ. Προσθ. Κατασκ.",
    Semester: 8,
    Room: "Β02",
    Code: 10152,
    Mon: [],
    Tue: [],
    Wed: [12, 13, 14],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Ακαδ. Αγγλικά Ι",
    Semester: 8,
    Room: "Β12",
    Code: 4011,
    Mon: [],
    Tue: [],
    Wed: [16, 17],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Σχεδίαση Πληροφορίας",
    Semester: 8,
    Room: "Β13",
    Code: 8802,
    Mon: [],
    Tue: [],
    Wed: [16, 17, 18, 19],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Ακαδ. Αγγλικά ΙΙ",
    Semester: 8,
    Room: "Β12",
    Code: 10200,
    Mon: [],
    Tue: [],
    Wed: [18, 19],
    Thu: [],
    Fri: [],
  },
  {
    Name: "Ιστορία Design II",
    Semester: 2,
    Room: "Β02",
    Code: 2252,
    Mon: [],
    Tue: [],
    Wed: [],
    Thu: [14, 15],
    Fri: [12, 13],
  },
  {
    Name: "Αγγλικά-Ορολογία -Β",
    Semester: 2,
    Room: "Β02",
    Code: 2354,
    Mon: [],
    Tue: [],
    Wed: [],
    Thu: [16, 17, 18],
    Fri: [],
  },
  {
    Name: "Μαθηματικά ΙI",
    Semester: 2,
    Room: "Π11",
    Code: 3453,
    Mon: [],
    Tue: [],
    Wed: [],
    Thu: [19, 20],
    Fri: [15, 16, 17],
  },
  {
    Name: "Σχεδίαση για όλους",
    Semester: 8,
    Room: "Β13",
    Code: 7154,
    Mon: [],
    Tue: [],
    Wed: [],
    Thu: [9, 10, 11, 12],
    Fri: [],
  },
  {
    Name: "Αισθ.Συναισθ. Σχεδ. (Θ)",
    Semester: 8,
    Room: "Β13",
    Code: 10302,
    Mon: [],
    Tue: [],
    Wed: [],
    Thu: [14, 15],
    Fri: [],
  },
  {
    Name: "Αισθ.Συναισθ. Σχεδ. (Ε)",
    Semester: 8,
    Room: "Β13",
    Code: 10302,
    Mon: [],
    Tue: [],
    Wed: [],
    Thu: [16],
    Fri: [],
  },
  {
    Name: "Σχεδ. Παγκ. Ιστό(Θ)",
    Semester: 8,
    Room: "ΗΥ",
    Code: 6404,
    Mon: [],
    Tue: [],
    Wed: [],
    Thu: [17, 18],
    Fri: [],
  },
  {
    Name: "Σχεδ. Παγκ. Ιστό(Ε)",
    Semester: 8,
    Room: "ΗΥ",
    Code: 6404,
    Mon: [],
    Tue: [],
    Wed: [],
    Thu: [19, 20],
    Fri: [],
  },
  {
    Name: "Στούντιο 4",
    Semester: 4,
    Room: "Ι12",
    Code: 4304,
    Mon: [],
    Tue: [],
    Wed: [],
    Thu: [],
    Fri: [9, 10, 11, 12, 13, 14],
  },
  {
    Name: "Διαδραστική Σχεδ. (Θ)",
    Semester: 6,
    Room: "Π11",
    Code: 4153,
    Mon: [],
    Tue: [],
    Wed: [],
    Thu: [],
    Fri: [9, 10, 11],
  },
  {
    Name: "Διαδραστική Σχεδ. (Ε)",
    Semester: 6,
    Room: "ΗΥ",
    Code: 4153,
    Mon: [],
    Tue: [],
    Wed: [],
    Thu: [],
    Fri: [12, 13],
  },
  {
    Name: "Ιστ. Τέχνης Ι",
    Semester: 8,
    Room: "Β02",
    Code: 5053,
    Mon: [],
    Tue: [],
    Wed: [],
    Thu: [],
    Fri: [9, 10, 11],
  },
  {
    Name: "Ψηφ. Πολιτιστική Κληρ.",
    Semester: 8,
    Room: "Β02",
    Code: 7901,
    Mon: [],
    Tue: [],
    Wed: [],
    Thu: [],
    Fri: [15, 16, 17],
  },
  {
    Name: "Ψηφ. Μορφές Αφήγ. (Θ)",
    Semester: 8,
    Room: "Β12",
    Code: 7554,
    Mon: [],
    Tue: [],
    Wed: [],
    Thu: [],
    Fri: [17, 18],
  },
  {
    Name: "Ψηφ. Μορφές Αφήγ. (Ε)",
    Semester: 8,
    Room: "ΗΥ",
    Code: 7554,
    Mon: [],
    Tue: [],
    Wed: [],
    Thu: [],
    Fri: [19, 20],
  },
];
