import Head from "next/head";
import styles from "styles/First.module.css";
import Lesson from "components/lesson.js";
import React, { useState, useEffect, useCallback } from "react";
import {
  hardcodedSemesterToggles,
  hardcodedLessons,
} from "components/hardcoded.js";
import CalendarMonthIcon from "@mui/icons-material/CalendarMonth";
import Link from "next/link";
// import Link from '@material-ui/core/Link';
function Home() {
  const [lessonsState, setLessonsState] = useState(hardcodedLessons);
  const [ects, setEcts] = useState(0);
  const [semesterToggle, setSemesterToggle] = useState(
    hardcodedSemesterToggles
  );

  const calculateEcts = () => {
    let num = 0;
    for (let i = 0; i < lessonsState.length; i++) {
      if (lessonsState[i].selected) {
        num += parseInt(lessonsState[i].ects);
      }
    }
    setEcts(num);
  };

  const calculateMandatory = () => {
    let num = 0;
    for (let i = 0; i < lessonsState.length; i++) {
      if (
        lessonsState[i].selected == false &&
        lessonsState[i].type == "Υποχρεωτικό (Υ)"
      ) {
        num += parseInt(lessonsState[i].ects);
      }
    }
    return num;
  };

  const semester = (i: number) => {
    return (
      <div>
        {lessonsState.map((lesson) => {
          return (
            <div key={lesson.name}>
              {parseInt(lesson.semester) == i ? (
                <Lesson data={lesson} onClick={calculateEcts} />
              ) : (
                <div></div>
              )}
            </div>
          );
        })}
      </div>
    );
  };

  const handleClick = (j: number) => {
    let liss = semesterToggle;
    liss[j] = !semesterToggle[j];

    for (let i = 0; i < lessonsState.length; i++) {
      if (parseInt(lessonsState[i].semester) == j + 1) {
        lessonsState[i].selected = liss[j];
      }
    }

    setSemesterToggle(liss);
    console.log(semesterToggle);
    // onClick();
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Link href="/programme">
          <CalendarMonthIcon className={styles.calendarIcon} />
        </Link>

        <div className={styles.container}>
          {[...Array(10)].map((_, i) => (
            <div className={styles.semester}>
              Εξάμηνο {i + 1}
              <span>
                {/* <input type="checkbox" id="a" /> */}
                <div
                  onClick={() => handleClick(i)}
                  className={
                    semesterToggle[i]
                      ? styles.semesterSelected
                      : styles.semesterUnselected
                  }
                >
                  box
                </div>
              </span>
              <div>{semester(i + 1)}</div>
            </div>
          ))}
        </div>

        <div className={styles.containerRight}>
          <div className={styles.ects}>ECTS = {ects}</div>
          {300 - ects > 0 || calculateMandatory() > 0 ? (
            <div className={styles.ects2}>Υπολειπόμενα ECTS = {300 - ects}</div>
          ) : (
            <div className={styles.ectsPassed}>
              <img
                className={styles.smiley}
                src="/smiley.svg"
                alt="Graduated Happily"
              />
            </div>
          )}
          {lessonsState.map((lesson) => {
            return (
              <div>
                {lesson.selected == false &&
                lesson.type == "Υποχρεωτικό (Υ)" ? (
                  <div className={styles.additionContainer}>
                    <div className={styles.additionName}>{lesson.name}</div>
                    <div className={styles.additionEcts}>{lesson.ects}</div>
                  </div>
                ) : (
                  <div></div>
                )}
              </div>
            );
          })}

          {calculateMandatory() > 0 && (
            <div className={styles.line}>
              +<br />
              <hr />
              <div className={styles.result1Left}>{calculateMandatory()}</div>
              <div className={styles.result1Right}> ects από υποχρεωτικά</div>
              <div className={styles.ects}>
                ECTS = {ects + calculateMandatory()}
              </div>
              <div className={styles.ects2}>
                Υπολειπόμενα ECTS = {300 - ects - calculateMandatory()}
              </div>
            </div>
          )}
        </div>
      </main>

      <style jsx global>{`
        html,
        body {
          max-width: 100vw;
          overflow-y: overlay;
          // overflow-x: hidden;
        }
        body {
          color: black;
          background: white;
          margin: 0px;
          font-family: GeomLight;
        }
      `}</style>
    </>
  );
}

export default Home;
